name: cli

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: cli-${{ github.head_ref }}
  cancel-in-progress: true

env:
  DEBUG: 1

jobs:
  build:
    strategy:
      matrix:
        target: ['aarch64-apple-darwin', 'x86_64-apple-darwin']
    name: Build for ${{ matrix.target }}
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target ${{ matrix.target }}
  test:
    name: Test
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
