name: cli

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: cli-${{ github.head_ref }}
  cancel-in-progress: true

env:
  DEBUG: 1

jobs:
  build:
    name: Build in ${{ matrix.platform }}
    strategy:
      matrix:
        platform: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
  test:
    name: Test in ${{ matrix.platform }}
    strategy:
      matrix:
        platform: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
